#!/bin/bash

# Definir códigos de colores ANSI
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # Reset color

# Imprimir banner con colores
echo -e "${RED}                             ,---.-,                                     ,----, "
echo -e "${GREEN}                            '   ,'  '.               ,-.----.          ,/   .\`| "
echo -e "${YELLOW}     ,---,       ,----,    /   /      \   ,----..    \    /  \       ,\`   .'  : "
echo -e "${BLUE}  ,\`--.' |     .'   .' \  .   ;  ,/.  :  /   /   \   |   :    \    ;    ;     / "
echo -e "${MAGENTA} /    /  :   ,----,'    | '   |  | :  ; |   :     :  |   |  .\ : .'___,/    ,'  "
echo -e "${CYAN}:    |.' '   |    :  .  ; '   |  ./   : .   |  ;. /  .   :  |: | |    :     |   "
echo -e "${WHITE}\`----':  |   ;    |.'  /  |   :       , .   ; /--\`   |   |   \ : ;    |.';  ;   "
echo -e "${RED}   '   ' ;   \`----'/  ;    \   \     /  ;   | ;  __  |   : .   / \`----'  |  |   "
echo -e "${GREEN}   |   | |     /  ;  /      ;   ,   '\  |   : |.' .' ;   | |\`-'      '   :  ;   "
echo -e "${YELLOW}   '   : ;    ;  /  /-,    /   /      \ .   | '_.' : |   | ;         |   |  '   "
echo -e "${BLUE}   |   | '   /  /  /.\`|   .   ;  ,/.  : '   ; : \  | :   ' |         '   :  |   "
echo -e "${MAGENTA}   '   : | ./__;      :   '   |  | :  ; '   | '/  .' :   : :         ;   |.'    "
echo -e "${CYAN}   ;   |.' |   :    .'    '   |  ./   : |   :    /   |   | :         '---'      "
echo -e "${WHITE}   '---'   ;   | .'       |   :      /   \   \ .'    \`---'.|                    "
echo -e "${RED}           \`---'           \   \   .'     \`---\`        \`---\`                    "
echo -e "${NC}"
